base_url = "https://ningunx-presx-por-luchar.info"
compile_sass = true
build_search_index = false
title="Coordinaci√≥n Antirepresiva y por las Libertades"

taxonomies = [
    { name = "tags", fees = false, paginate_by = 10 },
]

[markdown]
highlight_code = true
[extra]
navbar_items = [
    { code = "es", nav_items = [
        { url = "$BASE_URL/", name = "Inicio" },
        { url = "$BASE_URL/posts", name = "Publicaciones" },
        { url = "$BASE_URL/tags", name = "Etiquetas" },
    ] },
]

[extra.favicon]
favicon_16x16 = "/icons/favicon-16x16.png"
favicon_32x32 = "/icons/favicon-32x32.png"
apple_touch_icon = "/icons/apple-touch-icon.png"
safari_pinned_tab = "/icons/safari-pinned-tab.svg"
webmanifest = "/icons/site.webmanifest"

# Author details
[extra.author]
name = ""
avatar = "images/avatar.png"

# Social links